# use an official mevan image to build the spring boot app
FROM maven:3.8.5-openjdk-17 AS build

#set the working directory
WORKDIR /app

# copy the pom.xml and install dependencies
COPY pom.xml .
RUN mvn dependency:go-offline

# copy the source code and build the application
COPY src ./src
RUN mvn package -DskipTests

#use an official openjdk image to run the application
FROM eclipse-temurin:17-jdk-jammy

#set the working directory
WORKDIR /app

#build the build JAR file from the build stage
COPY --from=build /app/target/backend-0.0.1-SNAPSHOT.jar .

#expose port 5050
EXPOSE 5050

#specify the command to run the application
ENTRYPOINT ["java","-jar","/app/backend-0.0.1-SNAPSHOT.jar"]